server:
    port: 8080

logging:
    level:
        ROOT: INFO

github:
    api:
        url: https://api.github.com/repos
        connectionTimeout: 5000
        socketTimeout: 2000
        requestTimeout: 5000
        maxRedirects: 0
        expectContinue : FALSE

