server:
    port: 8080

logging:
    level:
        ROOT: INFO

github:
    api:
        url: https://api.github.com/repos
        connectionTimeout: 4
        socketTimeout: 2
        requestTimeout: 4
        maxRedirects: 0
        expectContinue: FALSE
        retriesCounter: 3
        retriesTimeout: 5

spring:
    jackson:
        serialization:
            WRITE_DATES_AS_TIMESTAMPS: FALSE
